# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/devon/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),devon)

$(call add-radio-file-sha1-checked,radio/bluetooth.img,05bf057f2ef764ca62c6410bce7678c112ebfc16)
$(call add-radio-file-sha1-checked,radio/modem.img,0d5e959e0869ca5b3c9998591e066601a5933f89)
$(call add-radio-file-sha1-checked,radio/abl.img,a788af792b23ad06accf9b4db3647cd0d174f8ac)
$(call add-radio-file-sha1-checked,radio/devcfg.img,40ccf81add04737d0ecb14c168190f5bb63f6108)
$(call add-radio-file-sha1-checked,radio/dsp.img,e696f95a5b672f1b1355745ca05840b098cb6775)
$(call add-radio-file-sha1-checked,radio/fsg.img,619cd6452b77e09a28ec2d30a37f41e76a807ecc)
$(call add-radio-file-sha1-checked,radio/hyp.img,77daa6e9a25c1a756d3ab8905b6756655afa448b)
$(call add-radio-file-sha1-checked,radio/keymaster.img,f51a12173f34247ef3d7b4afe371a6807fdf3967)
$(call add-radio-file-sha1-checked,radio/logo.img,25a2e28e9afe14fa5f3182876b32875cd2b2403a)
$(call add-radio-file-sha1-checked,radio/prov.img,f3dc635b2d5c55af45c0a77b1afb62587585d894)
$(call add-radio-file-sha1-checked,radio/qupfw.img,0ba12afc2a336bc1f462acd653a72ceb2d63ab6c)
$(call add-radio-file-sha1-checked,radio/rpm.img,8156aa41028fedd83f32858d355d1f24d2efce0d)
$(call add-radio-file-sha1-checked,radio/storsec.img,b43cede859d6660e57baa0e48279dcd38c499c10)
$(call add-radio-file-sha1-checked,radio/tz.img,f7083bf7ccfb8a5442f9a294fccb936013af6867)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,6161b48bba81f19e5c6d0a929f05e1acf840b3f2)
$(call add-radio-file-sha1-checked,radio/xbl.img,6e55f6c5849b3a1916930cc28d73fef348fa6f42)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,3f52d34dcee381589f2c0c0920f7ede2ce806ceb)

endif
